apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: vgo-monitoring
data:
  jaeger.yaml: |
    # Jaeger configuration
    query:
      base-path: /
      log-level: info
      ui-config: /etc/jaeger/ui.json
    
    collector:
      zipkin:
        host-port: :9411
      grpc:
        host-port: :14250
      http:
        host-port: :14268
    
    agent:
      jaeger:
        thrift-compact:
          host-port: :6831
        thrift-binary:
          host-port: :6832
        grpc:
          host-port: :14250
  
  ui.json: |
    {
      "monitor": {
        "menuEnabled": true
      },
      "dependencies": {
        "menuEnabled": true
      },
      "archiveEnabled": true,
      "tracking": {
        "gaID": "UA-000000-2",
        "trackErrors": true
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: vgo-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: vgo-monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.47
        ports:
        - containerPort: 16686  # Jaeger UI
          name: ui
        - containerPort: 14268  # HTTP collector
          name: http-collector
        - containerPort: 14250  # gRPC collector
          name: grpc-collector
        - containerPort: 6831   # UDP thrift compact
          name: thrift-compact
          protocol: UDP
        - containerPort: 6832   # UDP thrift binary
          name: thrift-binary
          protocol: UDP
        - containerPort: 9411   # Zipkin compatible
          name: zipkin
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: SPAN_STORAGE_TYPE
          value: "badger"
        - name: BADGER_EPHEMERAL
          value: "false"
        - name: BADGER_DIRECTORY_VALUE
          value: "/badger/data"
        - name: BADGER_DIRECTORY_KEY
          value: "/badger/key"
        - name: QUERY_BASE_PATH
          value: "/"
        - name: JAEGER_DISABLED
          value: "false"
        volumeMounts:
        - name: jaeger-storage
          mountPath: /badger
        - name: jaeger-config
          mountPath: /etc/jaeger
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: jaeger-storage
        persistentVolumeClaim:
          claimName: jaeger-pvc
      - name: jaeger-config
        configMap:
          name: jaeger-config
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: vgo-monitoring
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: 16686
    protocol: TCP
    name: ui
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: http-collector
  - port: 14250
    targetPort: 14250
    protocol: TCP
    name: grpc-collector
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: thrift-compact
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: thrift-binary
  - port: 9411
    targetPort: 9411
    protocol: TCP
    name: zipkin
  selector:
    app: jaeger
---
# Jaeger Agent DaemonSet for collecting traces from applications
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: vgo-monitoring
  labels:
    app: jaeger-agent
spec:
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.47
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 14271
          name: admin-http
        args:
        - --reporter.grpc.host-port=jaeger:14250
        - --reporter.type=grpc
        - --agent.tags=cluster=vgo-k8s
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 5
          periodSeconds: 5
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: vgo-monitoring
  labels:
    app: jaeger-agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5775
    targetPort: 5775
    protocol: UDP
    name: zk-compact-trft
  - port: 5778
    targetPort: 5778
    protocol: TCP
    name: config-rest
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: jg-compact-trft
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: jg-binary-trft
  - port: 14271
    targetPort: 14271
    protocol: TCP
    name: admin-http
  selector:
    app: jaeger-agent