apiVersion: v1
kind: ConfigMap
metadata:
  name: vgo-notify-config
  namespace: vgo-microservices
data:
  config.yaml: |
    server:
      grpc:
        port: 9092
        network: tcp
        timeout: 30s
      http:
        port: 8082
        network: tcp
        timeout: 30s
        cors:
          allow_origins: ["*"]
          allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allow_headers: ["*"]
    
    database:
      driver: postgres
      dsn: "postgres://vgo_user:vgo_password@postgres:5432/vgo_notify?sslmode=disable"
      max_open_conns: 25
      max_idle_conns: 10
      conn_max_lifetime: 300s
    
    redis:
      addr: "redis:6379"
      password: "vgo_redis_password"
      db: 1
      pool_size: 10
      min_idle_conns: 5
    
    log:
      level: info
      format: json
      output: stdout
    
    tracing:
      jaeger:
        endpoint: "http://jaeger:14268/api/traces"
        service_name: "vgo-notify"
        sample_rate: 0.1
    
    metrics:
      prometheus:
        enabled: true
        path: "/metrics"
        port: 9093
    
    notification:
      email:
        smtp:
          host: "smtp.gmail.com"
          port: 587
          username: "your-email@gmail.com"
          password: "your-app-password"
          from: "VGO System <noreply@vgo.local>"
        templates_dir: "/app/templates"
      sms:
        provider: "twilio"
        account_sid: "your-twilio-account-sid"
        auth_token: "your-twilio-auth-token"
        from_number: "+1234567890"
      webhook:
        timeout: 30s
        retry_attempts: 3
        retry_delay: 5s
      queue:
        workers: 5
        batch_size: 10
        poll_interval: 1s
        max_retry: 3
        retry_delay: 30s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vgo-notify
  namespace: vgo-microservices
  labels:
    app: vgo-notify
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vgo-notify
      version: v1
  template:
    metadata:
      labels:
        app: vgo-notify
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9093"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: vgo-notify
        image: vgo-notify:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        - containerPort: 9092
          name: grpc
          protocol: TCP
        - containerPort: 9093
          name: metrics
          protocol: TCP
        env:
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: templates
          mountPath: /app/templates
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          grpc:
            port: 9092
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: 9092
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          grpc:
            port: 9092
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: config
        configMap:
          name: vgo-notify-config
      - name: templates
        configMap:
          name: vgo-notify-templates
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: vgo-notify-grpc
  namespace: vgo-microservices
  labels:
    app: vgo-notify
    service: grpc
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: grpc
  selector:
    app: vgo-notify
---
apiVersion: v1
kind: Service
metadata:
  name: vgo-notify-http
  namespace: vgo-microservices
  labels:
    app: vgo-notify
    service: http
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: vgo-notify
---
apiVersion: v1
kind: Service
metadata:
  name: vgo-notify-metrics
  namespace: vgo-microservices
  labels:
    app: vgo-notify
    service: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: metrics
  selector:
    app: vgo-notify
---
# Notification Templates ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: vgo-notify-templates
  namespace: vgo-microservices
data:
  access_key_expiration.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Access Key Expiration Warning</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { text-align: center; margin-bottom: 30px; }
            .warning { background-color: #fff3cd; border: 1px solid #ffeaa7; color: #856404; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
            .details { background-color: #f8f9fa; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
            .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Access Key Expiration Warning</h1>
            </div>
            <div class="warning">
                <strong>Warning:</strong> Your access key is about to expire!
            </div>
            <div class="details">
                <p><strong>Access Key ID:</strong> {{.AccessKeyID}}</p>
                <p><strong>Expires At:</strong> {{.ExpiresAt}}</p>
                <p><strong>Days Remaining:</strong> {{.DaysRemaining}}</p>
            </div>
            <p>Please rotate your access key before it expires to avoid service interruption.</p>
            <div class="footer">
                <p>This is an automated message from VGO IAM System.</p>
            </div>
        </div>
    </body>
    </html>
  access_key_rotated.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Access Key Rotated Successfully</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { text-align: center; margin-bottom: 30px; }
            .success { background-color: #d4edda; border: 1px solid #c3e6cb; color: #155724; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
            .details { background-color: #f8f9fa; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
            .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>Access Key Rotated Successfully</h1>
            </div>
            <div class="success">
                <strong>Success:</strong> Your access key has been rotated successfully!
            </div>
            <div class="details">
                <p><strong>Access Key ID:</strong> {{.AccessKeyID}}</p>
                <p><strong>Rotated At:</strong> {{.RotatedAt}}</p>
                <p><strong>New Expiration:</strong> {{.NewExpiresAt}}</p>
            </div>
            <p>Your new access key is now active. Please update your applications with the new credentials.</p>
            <div class="footer">
                <p>This is an automated message from VGO IAM System.</p>
            </div>
        </div>
    </body>
    </html>
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vgo-notify-hpa
  namespace: vgo-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vgo-notify
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vgo-notify-pdb
  namespace: vgo-microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vgo-notify