apiVersion: v2
name: vgo-microservices
description: VGO微服务架构Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - microservices
  - iam
  - notification
  - golang
  - grpc

home: https://github.com/vgo/microservices
sources:
  - https://github.com/vgo/vgo-iam
  - https://github.com/vgo/vgo-notify

maintainers:
  - name: VGO Team
    email: team@vgo.com

dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.3.7"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "15.18.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled

annotations:
  category: Microservices
  licenses: Apache-2.0